config/routes.rb
Rails.application.routes.draw do
  resources :mains
  root 'mains#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/main.rb
class Main < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: [:show, :edit, :update, :destroy]

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: 'Main was successfully created.' }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1
  # PATCH/PUT /mains/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to @main, notice: 'Main was successfully updated.' }
        format.json { render :show, status: :ok, location: @main }
      else
        format.html { render :edit }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url, notice: 'Main was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_params
      params.require(:main).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlwStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mains/_form.html.erb
<%= form_for(main) do |f| %>
  <% if main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
      <% main.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mains/edit.html.erb
<h1>Editing Main</h1>

<%= render 'form', main: @main %>

<%= link_to 'Show', @main %> |
<%= link_to 'Back', mains_path %>

app/views/mains/index.html.erb
<div id="main">
<!-- header begins -->
<div id="header">
    <div id="buttons">
      <div class="but"><a href="#" class="razd_but"  title="">Home</a></div>
      <div class="but"><a href="#" class="razd_but" title="">Blog</a></div>
      <div class="but"><a href="#" class="razd_but" title="">Gallery</a></div>
      <div class="but"><a href="#" class="razd_but" title="">About Us</a></div>
      <div ><a href="#" title="">Contact Us</a></div>
    </div>
    <div id="logo"><a href="#">metamorph_camomile</a>
    <h2><a href="http://www.metamorphozis.com/" id="metamorph">Design by Metamorphosis Design</a></h2>
  </div>
</div>
<!-- header ends -->
    <div id="cont_top">
    <div id="cont_bot">
        <!-- content begins -->
        <div id="content">
          <div id="razd">
            <div id="left">
                  <h1>Company News</h1>
                    <div class="list"><span class="dat">05-11-2009 </span><br /><span>Lorem ipsum dolor sit amet.</span><br />
                        Consectetur adipiscing elit. Ut consectetur tempor augue sit amet suscipit. Vivamus dictum, enim eu semper viverra, est sapien lobortis nisi, sit amet...
                      <div class="read"><a href="#">
                                              <%= image_tag("but_read.gif", :alt => "rss feed") %>

                      <!-- <img src="images/but_read.gif" alt="" /> -->
                      </a></div>
                    </div>
              <div class="dot"></div>
                    <div class="list"><span class="dat">05-11-2009 </span><br /><span>Lorem ipsum dolor sit amet.</span><br />
                        Consectetur adipiscing elit. Ut consectetur tempor augue sit amet suscipit. Vivamus dictum, enim eu semper viverra, est sapien lobortis nisi, sit amet...
                        <div class="read"><a href="#"><%= image_tag("but_read.gif", :alt => "rss feed") %></a></div>
                    </div>
            </div>
            <div id="center">
                  <h1>Metamorphosis Design</h1>
                    <div class="text">
                        <%= image_tag("img1.jpg", :alt => "rss feed") %>
                        <span class="color">Sed elementum auctor posuere.</span> <br />
                        Morbi adipiscing velit convallis purus gravida eu semper urna tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent quis neque lectus, vitae consequat urna. Ves-tibulum ac elementum tellus. Vivamus faucibus cursus...</div>
                    <div class="read"><a href="#"><%= image_tag("but_read.gif", :alt => "rss feed") %></a></div><br /> 
                    <div class="text">
                        <%= image_tag("img2.jpg", :alt => "rss feed") %>
                        <!-- <img src="images/img2.jpg" width="161" height="99" class="img" alt=""  /> -->
                        <span class="color">Nunc feugiat lobortis interdum. </span> <br />
                  Vestibulum ipsum mauris, fermentum vel condimentum at, accumsan sit amet eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eleifend tincidunt facilisis. Nullam consequat, magna eget congue... </div>
                    <div class="read"><a href="#"><%= image_tag("but_read.gif", :alt => "rss feed") %></a></div><br /> 
                    <div class="text">
                        <%= image_tag("img3.jpg", :alt => "rss feed") %>
                        <!-- <img src="images/img3.jpg" width="161" height="99" class="img" alt=""  /> -->
                        <span class="color">Aenean id tellus arcu. </span> <br />
                  Aenean sit amet quam tempor est pharetra dapibus sed ut metus. Nunc pulvinar mollis felis, eget ullamcorper eros rutrum rutrum. Sed non lacus a augue hendrerit mattis. Sed sagittis fermentum mi, id euismod urna... </div>
                    <div class="read"><a href="#"><%= image_tag("but_read.gif", :alt => "rss feed") %></a></div><br /> 
            </div>
            <div class="right">
                <h1>Categories</h1>
              <ul>
                <li><a href="">Fusce id turpis non ante porttitor  </a></li>
                <li><a href="">In a nibh est, in rutrum elit.  </a></li>
                <li><a href="">In id sapien augue, id ornare leo.  </a></li>
                <li><a href="">Nunc quis nibh sed nisi blandit. </a></li>
                <li><a href="">Etiam nec tortor erat, eu tincidnt</a></li>
                <li><a href="">Etiam bibendum velit sed mi </a></li>
                <li><a href="">Nunc ac ante bibendum erat </a></li>
                <li><a href="">Donec ut nulla ligula, sit amet </a></li>
                <li><a href="">Suspendisse vehicula massa </a></li>
               </ul><br />
            </div>
            <div class="right">
                <h1>Meta</h1>
              <ul>
                <li><a href="">Proin hendrerit arcu ut nibh malesuada id bibendum sem</a></li>
                <li><a href="">Donec ut nulla ligula, sit amet molestie sapien.</a></li>
                <li><a href="">Suspendisse vehicula massa at erat lacinia semper. </a></li>
              </ul>
            </div>
            <div style="clear: both">

            <img src="images/spaser.gif" alt="" width="1" height="1" /></div>
          </div>
        </div>
    </div>
    </div>
    <!-- content ends -->
    <!-- footer begins -->
    <div id="footer">
  Copyright  2009. Designed by <a href="http://www.metamorphozis.com/" title="Flash Templates">Flash Templates</a><br />
    <a href="#">Privacy Policy</a> | <a href="#">Terms of Use</a> | <a href="http://validator.w3.org/check/referer" title="This page validates as XHTML 1.0 Transitional"><abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="This page validates as CSS"><abbr title="Cascading Style Sheets">CSS</abbr></a></div>
<!-- footer ends -->
</div>



<div id="overlay">
    <div class="popup">
        <h1 class="h1">Ку:)</h1>
        <button class="close" title="Закрыть" onclick="document.getElementById('overlay').style.display='none';">Закрыть</button>
    </div>
</div>


<style type="text/css">
  #overlay {
    position: fixed;
    top: 0;
    left: 0;
    display: none;
    width: 100%;
    height: 100%;
    background: #6d6c6c;
    opacity: 0.9;
    z-index: 998;
 }
  .popup{
    z-index: 999;
    background-color: black;
        opacity: 1;
    position: relative;
    top: 30%;
    width: 600px;
    height:172px;
    left: 30%;
            border-radius: 20px;

    /*right: 30%;*/
  }
  .h1{
    position: relative;
    top: 40px;
    color: white;
    font-size: 100px;
  }
  .close{
        position: relative;
        bottom: -75px;
        left: 5%;
        background-color: white;
        border-radius: 10px;
        width: 90%;
        padding: 10px;
  }
</style>
<script type="text/javascript">
  var delay_popup = 10;
  setTimeout("document.getElementById('overlay').style.display='block'", delay_popup);
</script>

app/views/mains/new.html.erb
<h1>New Main</h1>

<%= render 'form', main: @main %>

<%= link_to 'Back', mains_path %>

app/views/mains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @main.name %>
</p>

<%= link_to 'Edit', edit_main_path(@main) %> |
<%= link_to 'Back', mains_path %>